v25.12.2--fix bugs

diff --git a/.github/workflows/build-openwrt.yml b/.github/workflows/build-openwrt.yml
--- a/.github/workflows/build-openwrt.yml
+++ b/.github/workflows/build-openwrt.yml
@@ -102,7 +102,8 @@ jobs:
       run: |
         cd openwrt
         echo -e "MyMark ... $(nproc) thread compile..."
-        make -j$(nproc) V=s && echo "status=success" >> $GITHUB_OUTPUT || { echo "status=failed" >> $GITHUB_OUTPUT; exit 1; }
+        make -j$(nproc) || make -j$(nproc) V=s || { echo "status=failed" >> $GITHUB_OUTPUT; exit 1; }
+        echo "status=success" >> $GITHUB_OUTPUT
         echo "FILE_DATE=_$(date +"%Y%m%d%H%M")" >> $GITHUB_ENV
 
     - name: Get device name
@@ -117,7 +118,7 @@ jobs:
       run: df -hT
 
     - name: Upload bin directory
-      uses: actions/upload-artifact@v4
+      uses: actions/upload-artifact@v4.12.0
       if: steps.compile.outputs.status == 'success' && env.UPLOAD_BIN_DIR == 'true'
       with:
         name: OpenWrt_bin${{ env.DEVICE_NAME }}${{ env.FILE_DATE }}
