fix bugs

diff --git a/.github/workflows/build-openwrt.yml b/.github/workflows/build-openwrt.yml
--- a/.github/workflows/build-openwrt.yml
+++ b/.github/workflows/build-openwrt.yml
@@ -102,11 +102,15 @@ jobs:
       run: |
         cd openwrt
         echo -e "MyMark ... $(nproc) thread compile..."
-        echo "make -j$(nproc) || make -j1 || make -j1 V=s  || echo -e 'MyMark ...Something Wrong!' "
-        make -j1 V=s &&  echo "status=success" >>$GITHUB_OUTPUT ||  echo "status=failed" >>$GITHUB_OUTPUT
-        grep '^CONFIG_TARGET.*DEVICE.*=y' .config | sed -r 's/.*DEVICE_(.*)=y/\1/' > DEVICE_NAME
-        [ -s DEVICE_NAME ] && echo "DEVICE_NAME=_$(cat DEVICE_NAME)" >> $GITHUB_ENV
+        make -j$(nproc) V=s && echo "status=success" >> $GITHUB_OUTPUT || { echo "status=failed" >> $GITHUB_OUTPUT; exit 1; }
         echo "FILE_DATE=_$(date +"%Y%m%d%H%M")" >> $GITHUB_ENV
+
+    - name: Get device name
+      if: steps.compile.outputs.status == 'success'
+      run: |
+        cd openwrt
+        DEVICE=$(grep '^CONFIG_TARGET.*DEVICE.*=y' .config | sed -r 's/.*DEVICE_([^=]+)=y/\1/')
+        echo "DEVICE_NAME=_${DEVICE}" >> $GITHUB_ENV
 
     - name: Check space usage
       if: (!cancelled())
@@ -131,15 +135,6 @@ jobs:
         rm -rf packages
         echo "FIRMWARE=$PWD" >> $GITHUB_ENV
         echo "status=success" >> $GITHUB_OUTPUT
-
-    - name: Remove artifacts
-      id: removeart
-      uses: c-hive/gha-remove-artifacts@v2.0.0
-      if: env.REMOVE_ARTIFACTS == 'true' && !cancelled()
-      with:
-        age: '5 day'
-        skip-recent: 2
-        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
     - name: Upload firmware directory
       uses: actions/upload-artifact@v4
